[package]
name = "data_system_project"
version = "0.1.0"
edition = "2021"

[dependencies]
bloomfilter = "2.0"
memmap2 = "0.5"
lru = "0.10"  # Обновленная версия
lfu_cache = "1.3"
zstd = "0.11"
rayon = "1.5"
crossbeam = "0.8"
tempfile = "3.3"

[dev-dependencies]
tempfile = "3.3"